version: "3.0"

services:
  frontend:
    build:
      context: ./files/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - backend
    volumes:
      - ./mounts/site:/var/www/html
  backend:
    build:
      context: ./files/php
    networks:
      - backend
      - frontend
    depends_on:
      - database
    volumes:
      - ./mounts/site:/var/www/html
  database:
    build:
      context: ./files/db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: example_cms_db
    networks:
      - backend
    volumes:
      - ./mounts/database:/var/lib/mysql

networks:
  frontend: {}
  backend: {}
